name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the version you prefer
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Inject environment variables from secrets
      - name: Setup .env file
        run: |
          echo "VITE_APP_TMDB_API_KEY=${{ secrets.VITE_APP_TMDB_API_KEY }}" >> .env
          echo "VITE_APP_TMDB_API_TOKEN=${{ secrets.VITE_APP_TMDB_API_TOKEN }}" >> .env

      # 5. Build the project
      - name: Build project
        run: npm run build && cp ./404.html ./build

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
